# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/RL_18xx',
                'doc_host': 'https://Revys17.github.io',
                'git_url': 'https://github.com/Revys17/RL_18xx',
                'lib_path': 'RL_18xx'},
  'syms': {'RL_18xx.core': {'RL_18xx.core.foo': ('core.html#foo', 'RL_18xx/core.py')}}}
