# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/game/engine/game/00_base.ipynb.

# %% auto 0
__all__ = ['BaseGame', 'Meta']

# %% ../../../nbs/game/engine/game/00_base.ipynb 5
class BaseGame:
    def __init__():
        return None

# %% ../../../nbs/game/engine/game/00_base.ipynb 6
class Meta:
    def __init__():
        return None
