"""Write the advisor's test game: an 1830 game in progress, played by our own
engine and model and exported in the shape 18xx.games' GET /api/game/<id>
returns -- no human data, no names but "Player N", no chat, no timestamps.

The auction is a random legal one (``start_positions.random_start_actions``);
after it every seat samples its moves from ``--policy`` at ``--temperature``
(prices from its price head) for ``--decisions`` decisions, and the game stops
at the next operating turn that has to lay a tile, so the position has map
moves to recommend.

    CUDA_VISIBLE_DEVICES= python scripts/make_advisor_fixture.py --policy <ckpt.pth> \\
        --out tests/fixtures/advisor/game_1830_4p.json
"""

import argparse
import json
import random
import sys
from pathlib import Path

import numpy as np
import torch

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

GAME_ID = 123
FIRST_USER_ID = 101


def play(policy_path: str, decisions: int, temperature: float, seed: int, num_players: int):
    from rl18xx.agent.alphazero import policy_gradient as pg
    from rl18xx.agent.alphazero.mcts import _rust_encode
    from rl18xx.agent.alphazero.policy_selfplay import has_price_choice, load_checkpoint_model
    from rl18xx.agent.alphazero.start_positions import apply_actions, new_game, random_start_actions

    torch.manual_seed(seed)
    rng = np.random.default_rng(seed)
    model = load_checkpoint_model(policy_path)
    game = apply_actions(new_game(num_players), random_start_actions(num_players, random.Random(seed)))
    rs = game._game
    made = 0
    while not game.finished:
        legal = [int(i) for i in rs.factored_legal_indices()]
        decision = len(legal) > 1 or has_price_choice(rs, legal[0])
        if made >= decisions and decision and rs.active_step_type() == "LayTile":
            break
        if not decision:
            rs.apply_action_index(legal[0], pg.choose_price(game, legal[0], None, rng, 0.0)[0])
            continue
        with torch.no_grad():
            probs, _, _ = model.run_many_encoded([_rust_encode(game)])
        price_row = model.last_price_components["price_logits"][0].float().numpy()
        p = np.power(np.clip(probs[0].float().numpy()[legal].astype(np.float64), 1e-12, None), 1.0 / temperature)
        index = legal[int(rng.choice(len(legal), p=p / p.sum()))]
        rs.apply_action_index(index, pg.choose_price(game, index, price_row, rng, 0.0)[0])
        made += 1
    return game


def export(game, policy_path: str, seed: int) -> dict:
    """The game as 18xx.games serves it: user ids for the seats, ``user`` on every action."""
    from rl18xx.agent.alphazero.start_positions import new_game

    num_players = len(game.players)
    user = {pid: FIRST_USER_ID + pid - 1 for pid in range(1, num_players + 1)}
    players = [{"id": user[pid], "name": f"Player {pid}"} for pid in range(1, num_players + 1)]
    replay = new_game(num_players)  # to name the player behind each corporation / private action
    actions = []
    for i, raw in enumerate(game.raw_actions):
        action = {k: v for k, v in dict(raw).items() if k not in ("created_at", "user")}
        if action.get("entity_type") == "player":
            action["entity"] = user[int(action["entity"])]
            action["user"] = action["entity"]
        else:
            action["user"] = user[replay.get(action["entity_type"], action["entity"]).player().id]
        action["id"] = i + 1
        actions.append(action)
        replay.process_action(dict(raw))
    acting = [user[p.id] for p in game.active_players()]
    return {
        "fixture_format": {
            "source": "generated by scripts/make_advisor_fixture.py (no human data)",
            "policy": Path(policy_path).with_suffix("").as_posix().split("/")[-3:],
            "seed": seed,
        },
        "id": GAME_ID,
        "description": "advisor test game",
        "user": players[0],
        "players": players,
        "min_players": num_players,
        "max_players": num_players,
        "title": "1830",
        "settings": {"optional_rules": [], "seed": seed, "unlisted": False, "is_async": True},
        "status": "active",
        "turn": None,
        "round": game.round.__class__.__name__,
        "acting": acting,
        "result": {},
        "actions": actions,
        "loaded": True,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--policy", required=True)
    parser.add_argument("--decisions", type=int, default=150)
    parser.add_argument("--temperature", type=float, default=0.5)
    parser.add_argument("--seed", type=int, default=7)
    parser.add_argument("--players", type=int, default=4)
    parser.add_argument("--out", default="tests/fixtures/advisor/game_1830_4p.json")
    args = parser.parse_args()
    game = play(args.policy, args.decisions, args.temperature, args.seed, args.players)
    record = export(game, args.policy, args.seed)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(record, indent=None, separators=(",", ":")) + "\n")
    print(f"{out}: {len(record['actions'])} actions, {game.round.__class__.__name__}, acting {record['acting']}")


if __name__ == "__main__":
    main()
